const $=id=>document.getElementById(id);let state={events:[],rules:{},distributors:[]},editing=null;
const ruleFields=['PRÉ-VENDAS','FORMULÁRIO','SALA/LOCAL','CONVITE/DIVULGAÇÃO','LISTA DE PRESENÇA','FOTOS','INVESTIMENTO','META DE PARTICIPANTES'];
const defaultRules={'CERTIFICAÇÃO':{'PRÉ-VENDAS':'Obrigatório','FORMULÁRIO':'Obrigatório','SALA/LOCAL':'Obrigatório','CONVITE/DIVULGAÇÃO':'Obrigatório','LISTA DE PRESENÇA':'Obrigatório','FOTOS':'Obrigatório','INVESTIMENTO':'Opcional','META DE PARTICIPANTES':'Obrigatório'},'OMADA DAY':{'PRÉ-VENDAS':'Não se aplica','FORMULÁRIO':'Opcional','SALA/LOCAL':'Obrigatório','CONVITE/DIVULGAÇÃO':'Obrigatório','LISTA DE PRESENÇA':'Opcional','FOTOS':'Obrigatório','INVESTIMENTO':'Opcional','META DE PARTICIPANTES':'Opcional'},'WEBINAR':{'PRÉ-VENDAS':'Opcional','FORMULÁRIO':'Obrigatório','SALA/LOCAL':'Não se aplica','CONVITE/DIVULGAÇÃO':'Obrigatório','LISTA DE PRESENÇA':'Opcional','FOTOS':'Opcional','INVESTIMENTO':'Não se aplica','META DE PARTICIPANTES':'Opcional'},'WORKSHOP':{'PRÉ-VENDAS':'Opcional','FORMULÁRIO':'Obrigatório','SALA/LOCAL':'Obrigatório','CONVITE/DIVULGAÇÃO':'Obrigatório','LISTA DE PRESENÇA':'Obrigatório','FOTOS':'Obrigatório','INVESTIMENTO':'Opcional','META DE PARTICIPANTES':'Obrigatório'},'TREINAMENTO':{'PRÉ-VENDAS':'Obrigatório','FORMULÁRIO':'Obrigatório','SALA/LOCAL':'Opcional','CONVITE/DIVULGAÇÃO':'Obrigatório','LISTA DE PRESENÇA':'Obrigatório','FOTOS':'Obrigatório','INVESTIMENTO':'Opcional','META DE PARTICIPANTES':'Obrigatório'},'HAPPY HOUR':{'PRÉ-VENDAS':'Não se aplica','FORMULÁRIO':'Opcional','SALA/LOCAL':'Opcional','CONVITE/DIVULGAÇÃO':'Obrigatório','LISTA DE PRESENÇA':'Opcional','FOTOS':'Obrigatório','INVESTIMENTO':'Obrigatório','META DE PARTICIPANTES':'Opcional'},'VISITA':{'PRÉ-VENDAS':'Opcional','FORMULÁRIO':'Não se aplica','SALA/LOCAL':'Não se aplica','CONVITE/DIVULGAÇÃO':'Não se aplica','LISTA DE PRESENÇA':'Não se aplica','FOTOS':'Opcional','INVESTIMENTO':'Não se aplica','META DE PARTICIPANTES':'Não se aplica'}};
const defaultDists=[['AGIS','Foco','TIAGO DAMASCENO',''],['ALL NATIONS','Foco','TIAGO DAMASCENO','RONALDO'],['DCA','Foco','LARISSA MIRANDA',''],['DICOMP','VAD','LARISSA MIRANDA','RONALDO'],['DIPROSEG CE','Foco','TIAGO DAMASCENO',''],['DIPROSEG PA','Foco','TIAGO DAMASCENO',''],['ELETROTRANSOL','Não foco','TIAGO DAMASCENO',''],['FAGUNDEZ','Foco','TIAGO DAMASCENO',''],['GMI','VAD','DIEGO MACIEL',''],['MAZER','Foco','LARISSA MIRANDA',''],['MULTCABOS','Não foco','TIAGO DAMASCENO','RONALDO'],['ODERÇO','Foco','LARISSA MIRANDA','RONALDO'],['PAUTA','VAD','DIEGO MACIEL','RONALDO'],['SND','Foco','TIAGO DAMASCENO',''],['TEK','VAD','LARISSA MIRANDA','RONALDO'],['WDC','Foco','DIEGO MACIEL','']].map(x=>({name:x[0],category:x[1],executiveOmada:x[2],executiveVigi:x[3]}));
function msg(t,e=false){$('msg').innerHTML='<div class="statusbar '+(e?'err':'')+'">'+t+'</div>';setTimeout(()=>$('msg').innerHTML='',4500)}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function fmt(d){return d?d.split('-').reverse().join('/'):'Sem data'}function num(v){return Number(String(v||0).replace(/[^0-9,.-]/g,'').replace('.','').replace(',','.'))||0}function money(v){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
async function load(){const r=await fetch('/api/state',{cache:'no-store'});if(!r.ok)throw Error('Falha ao carregar');state=await r.json();state.events=state.events||[];if(!state.rules||!Object.keys(state.rules).length)state.rules=structuredClone(defaultRules);if(!state.distributors||!state.distributors.length)state.distributors=structuredClone(defaultDists);await save();}
async function save(){const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});if(!r.ok)throw Error('Falha ao salvar')}
function opts(a,all='Todos'){return '<option value="">'+all+'</option>'+a.map(v=>'<option>'+esc(v)+'</option>').join('')}function uniq(k){return [...new Set(state.events.map(e=>e[k]).filter(Boolean))].sort()}
function fillFilters(){['dashExec','calExec','fExec'].forEach(id=>$(id).innerHTML=opts(uniq('executive')));$('fStatus').innerHTML=opts(uniq('status'));$('fType').innerHTML=opts(uniq('type'))}
