async function init(){try{
const meRes=await fetch('/api/auth/me',{cache:'no-store'});
if(!meRes.ok){location.href='/login';return}
window.currentUser=await meRes.json();
$('userBadge').textContent=(currentUser.displayName||currentUser.username)+' · '+({admin:'Administrador',operator:'Operador',read_only:'Somente leitura'}[currentUser.role]||currentUser.role);
document.querySelectorAll('[data-admin-only="1"]').forEach(el=>el.style.display=currentUser.role==='admin'?'':'none');
await load();
$('newForm').innerHTML=formHTML({bu:'OMADA',status:'Em planejamento',internalApproval:'Não iniciado',clientExecution:'Não iniciado',readiness:'Em atenção'});
fillFilters();$('calMonth').value=new Date().toISOString().slice(0,7);renderAll();msg('Base online carregada: '+state.events.length+' eventos.');
}catch(e){msg('Não foi possível carregar a base online.',true)}}
$('nav').onclick=e=>{if(e.target.dataset.tab)showTab(e.target.dataset.tab)};$('dashExec').onchange=renderDash;$('dashBU').onchange=renderDash;$('calMonth').onchange=renderCalendar;$('calExec').onchange=renderCalendar;$('calBU').onchange=renderCalendar;
function moveMonth(delta){const val=$('calMonth').value||new Date().toISOString().slice(0,7);const [y,m]=val.split('-').map(Number);const d=new Date(y,m-1+delta,1);$('calMonth').value=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');renderCalendar()}
$('prevMonth').onclick=()=>moveMonth(-1);$('nextMonth').onclick=()=>moveMonth(1);
$('today').onclick=()=>{$('calMonth').value=new Date().toISOString().slice(0,7);renderCalendar()};['q','fExec','fStatus','fType','from','to'].forEach(id=>$(id).oninput=renderManage);$('clear').onclick=()=>{['q','fExec','fStatus','fType','from','to'].forEach(id=>$(id).value='');renderManage()};$('newForm').onsubmit=async e=>{e.preventDefault();const o=formObj(e.target),n=Math.max(0,...state.events.map(x=>Number((x.id||'').match(/(\d+)$/)?.[1]||0)))+1;o.id='EVT-'+new Date().getFullYear()+'-'+String(n).padStart(3,'0');state.events.push(o);await save();e.target.reset();renderAll();showTab('manage');msg('Evento criado e sincronizado.')};$('close').onclick=()=> $('modal').classList.remove('open');$('saveEdit').onclick=async()=>{const i=state.events.findIndex(x=>x.id===editing);state.events[i]={...state.events[i],...formObj($('editForm'))};await save();$('modal').classList.remove('open');renderAll();msg('Evento atualizado e sincronizado.')};$('delete').onclick=async()=>{if(confirm('Excluir este evento?')){state.events=state.events.filter(x=>x.id!==editing);await save();$('modal').classList.remove('open');renderAll();msg('Evento excluído.')}};$('addRule').onclick=async()=>{const n=prompt('Nome do tipo:');if(n){state.rules[n.toUpperCase()]=Object.fromEntries(ruleFields.map(k=>[k,'Opcional']));await save();renderRules()}};$('addDist').onclick=async()=>{state.distributors.push({name:'NOVO DISTRIBUIDOR',category:'Não foco',executiveOmada:'',executiveVigi:''});await save();renderDists()};$('logout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/login'};
$('print').onclick=()=>window.print();$('backup').onclick=()=>download(JSON.stringify(state,null,2),'agenda_backup.json','application/json');$('csv').onclick=()=>{const ks=Object.keys(state.events[0]||{});download('\ufeff'+[ks.join(';'),...state.events.map(e=>ks.map(k=>'"'+String(e[k]||'').replace(/"/g,'""')+'"').join(';'))].join('\n'),'agenda_eventos.csv','text/csv')};window.addEventListener('DOMContentLoaded',init);
